#!/bin/bash
cd $HOME
#sudo apt-get install Node.js
#sudo apt-get install -y npm
#sudo apt install node-grunt-cli
#npm install -g grunt-cli bower
#sudo apt update && sudo apt install libcanberra-gtk-module libgconf-2-4
wget https://ci.popcorntime.app/job/Popcorn-Time-Desktop/200/artifact/build/popcorn-time_0.3.10-28112f678_amd64.deb
sudo apt install $HOME/popcorn-time_0.3.10-28112f678_amd64.deb

